//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pl.lodz.p.ftims.edu.pai.web.TimesheetService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timesheet", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class Timesheet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pl.lodz.p.ftims.edu.pai.web.TimesheetService.Entry[] EntriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDay {
            get {
                return this.EndDayField;
            }
            set {
                if ((this.EndDayField.Equals(value) != true)) {
                    this.EndDayField = value;
                    this.RaisePropertyChanged("EndDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Entry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDay {
            get {
                return this.StartDayField;
            }
            set {
                if ((this.StartDayField.Equals(value) != true)) {
                    this.StartDayField = value;
                    this.RaisePropertyChanged("StartDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entry", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class Entry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateProject", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class CreateProject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateTask", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class CreateTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateEmployee", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class CreateEmployee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Audit", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class Audit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PreviousStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Change {
            get {
                return this.ChangeField;
            }
            set {
                if ((this.ChangeField.Equals(value) != true)) {
                    this.ChangeField = value;
                    this.RaisePropertyChanged("Change");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewStatus {
            get {
                return this.NewStatusField;
            }
            set {
                if ((this.NewStatusField.Equals(value) != true)) {
                    this.NewStatusField = value;
                    this.RaisePropertyChanged("NewStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreviousStatus {
            get {
                return this.PreviousStatusField;
            }
            set {
                if ((this.PreviousStatusField.Equals(value) != true)) {
                    this.PreviousStatusField = value;
                    this.RaisePropertyChanged("PreviousStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateTimesheet", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class CreateTimesheet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateEntry[] EntriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDay {
            get {
                return this.EndDayField;
            }
            set {
                if ((this.EndDayField.Equals(value) != true)) {
                    this.EndDayField = value;
                    this.RaisePropertyChanged("EndDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDay {
            get {
                return this.StartDayField;
            }
            set {
                if ((this.StartDayField.Equals(value) != true)) {
                    this.StartDayField = value;
                    this.RaisePropertyChanged("StartDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateEntry", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class CreateEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAudit", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class CreateAudit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PreviousStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimesheetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Change {
            get {
                return this.ChangeField;
            }
            set {
                if ((this.ChangeField.Equals(value) != true)) {
                    this.ChangeField = value;
                    this.RaisePropertyChanged("Change");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewStatus {
            get {
                return this.NewStatusField;
            }
            set {
                if ((this.NewStatusField.Equals(value) != true)) {
                    this.NewStatusField = value;
                    this.RaisePropertyChanged("NewStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((this.OperatorField.Equals(value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreviousStatus {
            get {
                return this.PreviousStatusField;
            }
            set {
                if ((this.PreviousStatusField.Equals(value) != true)) {
                    this.PreviousStatusField = value;
                    this.RaisePropertyChanged("PreviousStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Timesheet {
            get {
                return this.TimesheetField;
            }
            set {
                if ((this.TimesheetField.Equals(value) != true)) {
                    this.TimesheetField = value;
                    this.RaisePropertyChanged("Timesheet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Branch", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class Branch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBranch", Namespace="http://schemas.datacontract.org/2004/07/pl.lodz.p.ftims.edu.pai.central.dto")]
    [System.SerializableAttribute()]
    public partial class CreateBranch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimesheetService.IManagement")]
    public interface IManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProject", ReplyAction="http://tempuri.org/IManagement/GetProjectResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project GetProject(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProject", ReplyAction="http://tempuri.org/IManagement/GetProjectResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project> GetProjectAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjects", ReplyAction="http://tempuri.org/IManagement/GetProjectsResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[] GetProjects(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjects", ReplyAction="http://tempuri.org/IManagement/GetProjectsResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[]> GetProjectsAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetManagedProjects", ReplyAction="http://tempuri.org/IManagement/GetManagedProjectsResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[] GetManagedProjects(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetManagedProjects", ReplyAction="http://tempuri.org/IManagement/GetManagedProjectsResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[]> GetManagedProjectsAsync(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjectTimesheetsForPeriod", ReplyAction="http://tempuri.org/IManagement/GetProjectTimesheetsForPeriodResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[] GetProjectTimesheetsForPeriod(string id, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjectTimesheetsForPeriod", ReplyAction="http://tempuri.org/IManagement/GetProjectTimesheetsForPeriodResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[]> GetProjectTimesheetsForPeriodAsync(string id, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/QueryForProjects", ReplyAction="http://tempuri.org/IManagement/QueryForProjectsResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[] QueryForProjects(string query, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/QueryForProjects", ReplyAction="http://tempuri.org/IManagement/QueryForProjectsResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[]> QueryForProjectsAsync(string query, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateProject", ReplyAction="http://tempuri.org/IManagement/CreateProjectResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project CreateProject([System.ServiceModel.MessageParameterAttribute(Name="createProject")] pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateProject createProject1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateProject", ReplyAction="http://tempuri.org/IManagement/CreateProjectResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project> CreateProjectAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateProject createProject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteProject", ReplyAction="http://tempuri.org/IManagement/DeleteProjectResponse")]
        void DeleteProject(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteProject", ReplyAction="http://tempuri.org/IManagement/DeleteProjectResponse")]
        System.Threading.Tasks.Task DeleteProjectAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateProject", ReplyAction="http://tempuri.org/IManagement/UpdateProjectResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project UpdateProject(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateProject", ReplyAction="http://tempuri.org/IManagement/UpdateProjectResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project> UpdateProjectAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/SetProjectManager", ReplyAction="http://tempuri.org/IManagement/SetProjectManagerResponse")]
        void SetProjectManager(string projectId, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/SetProjectManager", ReplyAction="http://tempuri.org/IManagement/SetProjectManagerResponse")]
        System.Threading.Tasks.Task SetProjectManagerAsync(string projectId, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjectManager", ReplyAction="http://tempuri.org/IManagement/GetProjectManagerResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee GetProjectManager(string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjectManager", ReplyAction="http://tempuri.org/IManagement/GetProjectManagerResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> GetProjectManagerAsync(string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTask", ReplyAction="http://tempuri.org/IManagement/GetTaskResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task GetTask(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTask", ReplyAction="http://tempuri.org/IManagement/GetTaskResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task> GetTaskAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTasks", ReplyAction="http://tempuri.org/IManagement/GetTasksResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task[] GetTasks(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTasks", ReplyAction="http://tempuri.org/IManagement/GetTasksResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task[]> GetTasksAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/QueryForTaks", ReplyAction="http://tempuri.org/IManagement/QueryForTaksResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task[] QueryForTaks(string query, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/QueryForTaks", ReplyAction="http://tempuri.org/IManagement/QueryForTaksResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task[]> QueryForTaksAsync(string query, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateTask", ReplyAction="http://tempuri.org/IManagement/CreateTaskResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task CreateTask([System.ServiceModel.MessageParameterAttribute(Name="createTask")] pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateTask createTask1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateTask", ReplyAction="http://tempuri.org/IManagement/CreateTaskResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task> CreateTaskAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateTask createTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteTask", ReplyAction="http://tempuri.org/IManagement/DeleteTaskResponse")]
        void DeleteTask(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteTask", ReplyAction="http://tempuri.org/IManagement/DeleteTaskResponse")]
        System.Threading.Tasks.Task DeleteTaskAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateTask", ReplyAction="http://tempuri.org/IManagement/UpdateTaskResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task UpdateTask(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateTask", ReplyAction="http://tempuri.org/IManagement/UpdateTaskResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task> UpdateTaskAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployee", ReplyAction="http://tempuri.org/IManagement/GetEmployeeResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee GetEmployee(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployee", ReplyAction="http://tempuri.org/IManagement/GetEmployeeResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> GetEmployeeAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployees", ReplyAction="http://tempuri.org/IManagement/GetEmployeesResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[] GetEmployees(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployees", ReplyAction="http://tempuri.org/IManagement/GetEmployeesResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[]> GetEmployeesAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeSubordinates", ReplyAction="http://tempuri.org/IManagement/GetEmployeeSubordinatesResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[] GetEmployeeSubordinates(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeSubordinates", ReplyAction="http://tempuri.org/IManagement/GetEmployeeSubordinatesResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[]> GetEmployeeSubordinatesAsync(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeManager", ReplyAction="http://tempuri.org/IManagement/GetEmployeeManagerResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee GetEmployeeManager(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeManager", ReplyAction="http://tempuri.org/IManagement/GetEmployeeManagerResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> GetEmployeeManagerAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeTimesheetsForPeriod", ReplyAction="http://tempuri.org/IManagement/GetEmployeeTimesheetsForPeriodResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[] GetEmployeeTimesheetsForPeriod(string id, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeTimesheetsForPeriod", ReplyAction="http://tempuri.org/IManagement/GetEmployeeTimesheetsForPeriodResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[]> GetEmployeeTimesheetsForPeriodAsync(string id, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateEmployee", ReplyAction="http://tempuri.org/IManagement/CreateEmployeeResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee CreateEmployee([System.ServiceModel.MessageParameterAttribute(Name="createEmployee")] pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateEmployee createEmployee1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateEmployee", ReplyAction="http://tempuri.org/IManagement/CreateEmployeeResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> CreateEmployeeAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateEmployee createEmployee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteEmployee", ReplyAction="http://tempuri.org/IManagement/DeleteEmployeeResponse")]
        void DeleteEmployee(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteEmployee", ReplyAction="http://tempuri.org/IManagement/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateEmployee", ReplyAction="http://tempuri.org/IManagement/UpdateEmployeeResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee UpdateEmployee(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateEmployee", ReplyAction="http://tempuri.org/IManagement/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> UpdateEmployeeAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/AddSubordinate", ReplyAction="http://tempuri.org/IManagement/AddSubordinateResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[] AddSubordinate(string employeeId, string subordinateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/AddSubordinate", ReplyAction="http://tempuri.org/IManagement/AddSubordinateResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[]> AddSubordinateAsync(string employeeId, string subordinateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteSubordinate", ReplyAction="http://tempuri.org/IManagement/DeleteSubordinateResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[] DeleteSubordinate(string employeeId, string subordinateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteSubordinate", ReplyAction="http://tempuri.org/IManagement/DeleteSubordinateResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[]> DeleteSubordinateAsync(string employeeId, string subordinateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheet", ReplyAction="http://tempuri.org/IManagement/GetTimesheetResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet GetTimesheet(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheet", ReplyAction="http://tempuri.org/IManagement/GetTimesheetResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet> GetTimesheetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheets", ReplyAction="http://tempuri.org/IManagement/GetTimesheetsResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[] GetTimesheets(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheets", ReplyAction="http://tempuri.org/IManagement/GetTimesheetsResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[]> GetTimesheetsAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheetsNeedAction", ReplyAction="http://tempuri.org/IManagement/GetTimesheetsNeedActionResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[] GetTimesheetsNeedAction(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheetsNeedAction", ReplyAction="http://tempuri.org/IManagement/GetTimesheetsNeedActionResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[]> GetTimesheetsNeedActionAsync(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheetHistory", ReplyAction="http://tempuri.org/IManagement/GetTimesheetHistoryResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Audit[] GetTimesheetHistory(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheetHistory", ReplyAction="http://tempuri.org/IManagement/GetTimesheetHistoryResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Audit[]> GetTimesheetHistoryAsync(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateTimesheet", ReplyAction="http://tempuri.org/IManagement/CreateTimesheetResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet CreateTimesheet([System.ServiceModel.MessageParameterAttribute(Name="createTimesheet")] pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateTimesheet createTimesheet1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateTimesheet", ReplyAction="http://tempuri.org/IManagement/CreateTimesheetResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet> CreateTimesheetAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateTimesheet createTimesheet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/AcceptTimesheet", ReplyAction="http://tempuri.org/IManagement/AcceptTimesheetResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet AcceptTimesheet(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateAudit createAudit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/AcceptTimesheet", ReplyAction="http://tempuri.org/IManagement/AcceptTimesheetResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet> AcceptTimesheetAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateAudit createAudit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/RejectTimesheet", ReplyAction="http://tempuri.org/IManagement/RejectTimesheetResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet RejectTimesheet(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateAudit createAudit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/RejectTimesheet", ReplyAction="http://tempuri.org/IManagement/RejectTimesheetResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet> RejectTimesheetAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateAudit createAudit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetBranch", ReplyAction="http://tempuri.org/IManagement/GetBranchResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch GetBranch(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetBranch", ReplyAction="http://tempuri.org/IManagement/GetBranchResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch> GetBranchAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetBranchess", ReplyAction="http://tempuri.org/IManagement/GetBranchessResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch[] GetBranchess(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetBranchess", ReplyAction="http://tempuri.org/IManagement/GetBranchessResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch[]> GetBranchessAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateBranch", ReplyAction="http://tempuri.org/IManagement/CreateBranchResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch CreateBranch([System.ServiceModel.MessageParameterAttribute(Name="createBranch")] pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateBranch createBranch1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateBranch", ReplyAction="http://tempuri.org/IManagement/CreateBranchResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch> CreateBranchAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateBranch createBranch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteBranch", ReplyAction="http://tempuri.org/IManagement/DeleteBranchResponse")]
        void DeleteBranch(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteBranch", ReplyAction="http://tempuri.org/IManagement/DeleteBranchResponse")]
        System.Threading.Tasks.Task DeleteBranchAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateBranch", ReplyAction="http://tempuri.org/IManagement/UpdateBranchResponse")]
        pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch UpdateBranch(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateBranch", ReplyAction="http://tempuri.org/IManagement/UpdateBranchResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch> UpdateBranchAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch project);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManagementChannel : pl.lodz.p.ftims.edu.pai.web.TimesheetService.IManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagementClient : System.ServiceModel.ClientBase<pl.lodz.p.ftims.edu.pai.web.TimesheetService.IManagement>, pl.lodz.p.ftims.edu.pai.web.TimesheetService.IManagement {
        
        public ManagementClient() {
        }
        
        public ManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project GetProject(string id) {
            return base.Channel.GetProject(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project> GetProjectAsync(string id) {
            return base.Channel.GetProjectAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[] GetProjects(int start, int limit) {
            return base.Channel.GetProjects(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[]> GetProjectsAsync(int start, int limit) {
            return base.Channel.GetProjectsAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[] GetManagedProjects(string id, int start, int limit) {
            return base.Channel.GetManagedProjects(id, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[]> GetManagedProjectsAsync(string id, int start, int limit) {
            return base.Channel.GetManagedProjectsAsync(id, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[] GetProjectTimesheetsForPeriod(string id, string start, string end) {
            return base.Channel.GetProjectTimesheetsForPeriod(id, start, end);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[]> GetProjectTimesheetsForPeriodAsync(string id, string start, string end) {
            return base.Channel.GetProjectTimesheetsForPeriodAsync(id, start, end);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[] QueryForProjects(string query, int start, int limit) {
            return base.Channel.QueryForProjects(query, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project[]> QueryForProjectsAsync(string query, int start, int limit) {
            return base.Channel.QueryForProjectsAsync(query, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project CreateProject(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateProject createProject1) {
            return base.Channel.CreateProject(createProject1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project> CreateProjectAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateProject createProject) {
            return base.Channel.CreateProjectAsync(createProject);
        }
        
        public void DeleteProject(string id) {
            base.Channel.DeleteProject(id);
        }
        
        public System.Threading.Tasks.Task DeleteProjectAsync(string id) {
            return base.Channel.DeleteProjectAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project UpdateProject(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project project) {
            return base.Channel.UpdateProject(id, project);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project> UpdateProjectAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Project project) {
            return base.Channel.UpdateProjectAsync(id, project);
        }
        
        public void SetProjectManager(string projectId, string employeeId) {
            base.Channel.SetProjectManager(projectId, employeeId);
        }
        
        public System.Threading.Tasks.Task SetProjectManagerAsync(string projectId, string employeeId) {
            return base.Channel.SetProjectManagerAsync(projectId, employeeId);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee GetProjectManager(string projectId) {
            return base.Channel.GetProjectManager(projectId);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> GetProjectManagerAsync(string projectId) {
            return base.Channel.GetProjectManagerAsync(projectId);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task GetTask(string id) {
            return base.Channel.GetTask(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task> GetTaskAsync(string id) {
            return base.Channel.GetTaskAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task[] GetTasks(int start, int limit) {
            return base.Channel.GetTasks(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task[]> GetTasksAsync(int start, int limit) {
            return base.Channel.GetTasksAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task[] QueryForTaks(string query, int start, int limit) {
            return base.Channel.QueryForTaks(query, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task[]> QueryForTaksAsync(string query, int start, int limit) {
            return base.Channel.QueryForTaksAsync(query, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task CreateTask(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateTask createTask1) {
            return base.Channel.CreateTask(createTask1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task> CreateTaskAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateTask createTask) {
            return base.Channel.CreateTaskAsync(createTask);
        }
        
        public void DeleteTask(string id) {
            base.Channel.DeleteTask(id);
        }
        
        public System.Threading.Tasks.Task DeleteTaskAsync(string id) {
            return base.Channel.DeleteTaskAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task UpdateTask(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task project) {
            return base.Channel.UpdateTask(id, project);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task> UpdateTaskAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Task project) {
            return base.Channel.UpdateTaskAsync(id, project);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee GetEmployee(string id) {
            return base.Channel.GetEmployee(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> GetEmployeeAsync(string id) {
            return base.Channel.GetEmployeeAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[] GetEmployees(int start, int limit) {
            return base.Channel.GetEmployees(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[]> GetEmployeesAsync(int start, int limit) {
            return base.Channel.GetEmployeesAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[] GetEmployeeSubordinates(string id, int start, int limit) {
            return base.Channel.GetEmployeeSubordinates(id, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[]> GetEmployeeSubordinatesAsync(string id, int start, int limit) {
            return base.Channel.GetEmployeeSubordinatesAsync(id, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee GetEmployeeManager(string id) {
            return base.Channel.GetEmployeeManager(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> GetEmployeeManagerAsync(string id) {
            return base.Channel.GetEmployeeManagerAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[] GetEmployeeTimesheetsForPeriod(string id, string start, string end) {
            return base.Channel.GetEmployeeTimesheetsForPeriod(id, start, end);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[]> GetEmployeeTimesheetsForPeriodAsync(string id, string start, string end) {
            return base.Channel.GetEmployeeTimesheetsForPeriodAsync(id, start, end);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee CreateEmployee(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateEmployee createEmployee1) {
            return base.Channel.CreateEmployee(createEmployee1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> CreateEmployeeAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateEmployee createEmployee) {
            return base.Channel.CreateEmployeeAsync(createEmployee);
        }
        
        public void DeleteEmployee(string id) {
            base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(string id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee UpdateEmployee(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee employee) {
            return base.Channel.UpdateEmployee(id, employee);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee> UpdateEmployeeAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee employee) {
            return base.Channel.UpdateEmployeeAsync(id, employee);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[] AddSubordinate(string employeeId, string subordinateId) {
            return base.Channel.AddSubordinate(employeeId, subordinateId);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[]> AddSubordinateAsync(string employeeId, string subordinateId) {
            return base.Channel.AddSubordinateAsync(employeeId, subordinateId);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[] DeleteSubordinate(string employeeId, string subordinateId) {
            return base.Channel.DeleteSubordinate(employeeId, subordinateId);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Employee[]> DeleteSubordinateAsync(string employeeId, string subordinateId) {
            return base.Channel.DeleteSubordinateAsync(employeeId, subordinateId);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet GetTimesheet(string id) {
            return base.Channel.GetTimesheet(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet> GetTimesheetAsync(string id) {
            return base.Channel.GetTimesheetAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[] GetTimesheets(int start, int limit) {
            return base.Channel.GetTimesheets(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[]> GetTimesheetsAsync(int start, int limit) {
            return base.Channel.GetTimesheetsAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[] GetTimesheetsNeedAction(string id, int start, int limit) {
            return base.Channel.GetTimesheetsNeedAction(id, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet[]> GetTimesheetsNeedActionAsync(string id, int start, int limit) {
            return base.Channel.GetTimesheetsNeedActionAsync(id, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Audit[] GetTimesheetHistory(string id, int start, int limit) {
            return base.Channel.GetTimesheetHistory(id, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Audit[]> GetTimesheetHistoryAsync(string id, int start, int limit) {
            return base.Channel.GetTimesheetHistoryAsync(id, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet CreateTimesheet(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateTimesheet createTimesheet1) {
            return base.Channel.CreateTimesheet(createTimesheet1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet> CreateTimesheetAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateTimesheet createTimesheet) {
            return base.Channel.CreateTimesheetAsync(createTimesheet);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet AcceptTimesheet(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateAudit createAudit) {
            return base.Channel.AcceptTimesheet(id, createAudit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet> AcceptTimesheetAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateAudit createAudit) {
            return base.Channel.AcceptTimesheetAsync(id, createAudit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet RejectTimesheet(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateAudit createAudit) {
            return base.Channel.RejectTimesheet(id, createAudit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Timesheet> RejectTimesheetAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateAudit createAudit) {
            return base.Channel.RejectTimesheetAsync(id, createAudit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch GetBranch(string id) {
            return base.Channel.GetBranch(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch> GetBranchAsync(string id) {
            return base.Channel.GetBranchAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch[] GetBranchess(int start, int limit) {
            return base.Channel.GetBranchess(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch[]> GetBranchessAsync(int start, int limit) {
            return base.Channel.GetBranchessAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch CreateBranch(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateBranch createBranch1) {
            return base.Channel.CreateBranch(createBranch1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch> CreateBranchAsync(pl.lodz.p.ftims.edu.pai.web.TimesheetService.CreateBranch createBranch) {
            return base.Channel.CreateBranchAsync(createBranch);
        }
        
        public void DeleteBranch(string id) {
            base.Channel.DeleteBranch(id);
        }
        
        public System.Threading.Tasks.Task DeleteBranchAsync(string id) {
            return base.Channel.DeleteBranchAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch UpdateBranch(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch project) {
            return base.Channel.UpdateBranch(id, project);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch> UpdateBranchAsync(string id, pl.lodz.p.ftims.edu.pai.web.TimesheetService.Branch project) {
            return base.Channel.UpdateBranchAsync(id, project);
        }
    }
}
