//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pl.lodz.p.ftims.edu.pai.admin.AdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminService.IManagement")]
    public interface IManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProject", ReplyAction="http://tempuri.org/IManagement/GetProjectResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Project GetProject(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProject", ReplyAction="http://tempuri.org/IManagement/GetProjectResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project> GetProjectAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjects", ReplyAction="http://tempuri.org/IManagement/GetProjectsResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Project[] GetProjects(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjects", ReplyAction="http://tempuri.org/IManagement/GetProjectsResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project[]> GetProjectsAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetManagedProjects", ReplyAction="http://tempuri.org/IManagement/GetManagedProjectsResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Project[] GetManagedProjects(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetManagedProjects", ReplyAction="http://tempuri.org/IManagement/GetManagedProjectsResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project[]> GetManagedProjectsAsync(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjectTimesheetsForPeriod", ReplyAction="http://tempuri.org/IManagement/GetProjectTimesheetsForPeriodResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[] GetProjectTimesheetsForPeriod(string id, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjectTimesheetsForPeriod", ReplyAction="http://tempuri.org/IManagement/GetProjectTimesheetsForPeriodResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[]> GetProjectTimesheetsForPeriodAsync(string id, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/QueryForProjects", ReplyAction="http://tempuri.org/IManagement/QueryForProjectsResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Project[] QueryForProjects(string query, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/QueryForProjects", ReplyAction="http://tempuri.org/IManagement/QueryForProjectsResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project[]> QueryForProjectsAsync(string query, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateProject", ReplyAction="http://tempuri.org/IManagement/CreateProjectResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Project CreateProject([System.ServiceModel.MessageParameterAttribute(Name="createProject")] pl.lodz.p.ftims.edu.pai.central.dto.CreateProject createProject1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateProject", ReplyAction="http://tempuri.org/IManagement/CreateProjectResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project> CreateProjectAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateProject createProject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteProject", ReplyAction="http://tempuri.org/IManagement/DeleteProjectResponse")]
        void DeleteProject(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteProject", ReplyAction="http://tempuri.org/IManagement/DeleteProjectResponse")]
        System.Threading.Tasks.Task DeleteProjectAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateProject", ReplyAction="http://tempuri.org/IManagement/UpdateProjectResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Project UpdateProject(string id, pl.lodz.p.ftims.edu.pai.central.dto.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateProject", ReplyAction="http://tempuri.org/IManagement/UpdateProjectResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project> UpdateProjectAsync(string id, pl.lodz.p.ftims.edu.pai.central.dto.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/SetProjectManager", ReplyAction="http://tempuri.org/IManagement/SetProjectManagerResponse")]
        void SetProjectManager(string projectId, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/SetProjectManager", ReplyAction="http://tempuri.org/IManagement/SetProjectManagerResponse")]
        System.Threading.Tasks.Task SetProjectManagerAsync(string projectId, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjectManager", ReplyAction="http://tempuri.org/IManagement/GetProjectManagerResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Employee GetProjectManager(string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetProjectManager", ReplyAction="http://tempuri.org/IManagement/GetProjectManagerResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> GetProjectManagerAsync(string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTask", ReplyAction="http://tempuri.org/IManagement/GetTaskResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Task GetTask(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTask", ReplyAction="http://tempuri.org/IManagement/GetTaskResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task> GetTaskAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTasks", ReplyAction="http://tempuri.org/IManagement/GetTasksResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Task[] GetTasks(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTasks", ReplyAction="http://tempuri.org/IManagement/GetTasksResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task[]> GetTasksAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/QueryForTaks", ReplyAction="http://tempuri.org/IManagement/QueryForTaksResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Task[] QueryForTaks(string query, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/QueryForTaks", ReplyAction="http://tempuri.org/IManagement/QueryForTaksResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task[]> QueryForTaksAsync(string query, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateTask", ReplyAction="http://tempuri.org/IManagement/CreateTaskResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Task CreateTask([System.ServiceModel.MessageParameterAttribute(Name="createTask")] pl.lodz.p.ftims.edu.pai.central.dto.CreateTask createTask1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateTask", ReplyAction="http://tempuri.org/IManagement/CreateTaskResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task> CreateTaskAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateTask createTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteTask", ReplyAction="http://tempuri.org/IManagement/DeleteTaskResponse")]
        void DeleteTask(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteTask", ReplyAction="http://tempuri.org/IManagement/DeleteTaskResponse")]
        System.Threading.Tasks.Task DeleteTaskAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateTask", ReplyAction="http://tempuri.org/IManagement/UpdateTaskResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Task UpdateTask(string id, pl.lodz.p.ftims.edu.pai.central.dto.Task project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateTask", ReplyAction="http://tempuri.org/IManagement/UpdateTaskResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task> UpdateTaskAsync(string id, pl.lodz.p.ftims.edu.pai.central.dto.Task project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployee", ReplyAction="http://tempuri.org/IManagement/GetEmployeeResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Employee GetEmployee(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployee", ReplyAction="http://tempuri.org/IManagement/GetEmployeeResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> GetEmployeeAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployees", ReplyAction="http://tempuri.org/IManagement/GetEmployeesResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Employee[] GetEmployees(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployees", ReplyAction="http://tempuri.org/IManagement/GetEmployeesResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee[]> GetEmployeesAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeSubordinates", ReplyAction="http://tempuri.org/IManagement/GetEmployeeSubordinatesResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Employee[] GetEmployeeSubordinates(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeSubordinates", ReplyAction="http://tempuri.org/IManagement/GetEmployeeSubordinatesResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee[]> GetEmployeeSubordinatesAsync(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeManager", ReplyAction="http://tempuri.org/IManagement/GetEmployeeManagerResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Employee GetEmployeeManager(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeManager", ReplyAction="http://tempuri.org/IManagement/GetEmployeeManagerResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> GetEmployeeManagerAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeTimesheetsForPeriod", ReplyAction="http://tempuri.org/IManagement/GetEmployeeTimesheetsForPeriodResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[] GetEmployeeTimesheetsForPeriod(string id, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetEmployeeTimesheetsForPeriod", ReplyAction="http://tempuri.org/IManagement/GetEmployeeTimesheetsForPeriodResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[]> GetEmployeeTimesheetsForPeriodAsync(string id, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateEmployee", ReplyAction="http://tempuri.org/IManagement/CreateEmployeeResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Employee CreateEmployee([System.ServiceModel.MessageParameterAttribute(Name="createEmployee")] pl.lodz.p.ftims.edu.pai.central.dto.CreateEmployee createEmployee1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateEmployee", ReplyAction="http://tempuri.org/IManagement/CreateEmployeeResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> CreateEmployeeAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateEmployee createEmployee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteEmployee", ReplyAction="http://tempuri.org/IManagement/DeleteEmployeeResponse")]
        void DeleteEmployee(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteEmployee", ReplyAction="http://tempuri.org/IManagement/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateEmployee", ReplyAction="http://tempuri.org/IManagement/UpdateEmployeeResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Employee UpdateEmployee(string id, pl.lodz.p.ftims.edu.pai.central.dto.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateEmployee", ReplyAction="http://tempuri.org/IManagement/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> UpdateEmployeeAsync(string id, pl.lodz.p.ftims.edu.pai.central.dto.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/AddSubordinate", ReplyAction="http://tempuri.org/IManagement/AddSubordinateResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Employee[] AddSubordinate(string employeeId, string subordinateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/AddSubordinate", ReplyAction="http://tempuri.org/IManagement/AddSubordinateResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee[]> AddSubordinateAsync(string employeeId, string subordinateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteSubordinate", ReplyAction="http://tempuri.org/IManagement/DeleteSubordinateResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Employee[] DeleteSubordinate(string employeeId, string subordinateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteSubordinate", ReplyAction="http://tempuri.org/IManagement/DeleteSubordinateResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee[]> DeleteSubordinateAsync(string employeeId, string subordinateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheet", ReplyAction="http://tempuri.org/IManagement/GetTimesheetResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Timesheet GetTimesheet(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheet", ReplyAction="http://tempuri.org/IManagement/GetTimesheetResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet> GetTimesheetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheets", ReplyAction="http://tempuri.org/IManagement/GetTimesheetsResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[] GetTimesheets(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheets", ReplyAction="http://tempuri.org/IManagement/GetTimesheetsResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[]> GetTimesheetsAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheetsNeedAction", ReplyAction="http://tempuri.org/IManagement/GetTimesheetsNeedActionResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[] GetTimesheetsNeedAction(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheetsNeedAction", ReplyAction="http://tempuri.org/IManagement/GetTimesheetsNeedActionResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[]> GetTimesheetsNeedActionAsync(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheetHistory", ReplyAction="http://tempuri.org/IManagement/GetTimesheetHistoryResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Audit[] GetTimesheetHistory(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetTimesheetHistory", ReplyAction="http://tempuri.org/IManagement/GetTimesheetHistoryResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Audit[]> GetTimesheetHistoryAsync(string id, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateTimesheet", ReplyAction="http://tempuri.org/IManagement/CreateTimesheetResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Timesheet CreateTimesheet([System.ServiceModel.MessageParameterAttribute(Name="createTimesheet")] pl.lodz.p.ftims.edu.pai.central.dto.CreateTimesheet createTimesheet1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateTimesheet", ReplyAction="http://tempuri.org/IManagement/CreateTimesheetResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet> CreateTimesheetAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateTimesheet createTimesheet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/AcceptTimesheet", ReplyAction="http://tempuri.org/IManagement/AcceptTimesheetResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Timesheet AcceptTimesheet(string id, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/AcceptTimesheet", ReplyAction="http://tempuri.org/IManagement/AcceptTimesheetResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet> AcceptTimesheetAsync(string id, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/RejectTimesheet", ReplyAction="http://tempuri.org/IManagement/RejectTimesheetResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Timesheet RejectTimesheet(string id, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/RejectTimesheet", ReplyAction="http://tempuri.org/IManagement/RejectTimesheetResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet> RejectTimesheetAsync(string id, string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetBranch", ReplyAction="http://tempuri.org/IManagement/GetBranchResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Branch GetBranch(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetBranch", ReplyAction="http://tempuri.org/IManagement/GetBranchResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Branch> GetBranchAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetBranchess", ReplyAction="http://tempuri.org/IManagement/GetBranchessResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Branch[] GetBranchess(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/GetBranchess", ReplyAction="http://tempuri.org/IManagement/GetBranchessResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Branch[]> GetBranchessAsync(int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateBranch", ReplyAction="http://tempuri.org/IManagement/CreateBranchResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Branch CreateBranch([System.ServiceModel.MessageParameterAttribute(Name="createBranch")] pl.lodz.p.ftims.edu.pai.central.dto.CreateBranch createBranch1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/CreateBranch", ReplyAction="http://tempuri.org/IManagement/CreateBranchResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Branch> CreateBranchAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateBranch createBranch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteBranch", ReplyAction="http://tempuri.org/IManagement/DeleteBranchResponse")]
        void DeleteBranch(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/DeleteBranch", ReplyAction="http://tempuri.org/IManagement/DeleteBranchResponse")]
        System.Threading.Tasks.Task DeleteBranchAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateBranch", ReplyAction="http://tempuri.org/IManagement/UpdateBranchResponse")]
        pl.lodz.p.ftims.edu.pai.central.dto.Branch UpdateBranch(string id, pl.lodz.p.ftims.edu.pai.central.dto.Branch project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagement/UpdateBranch", ReplyAction="http://tempuri.org/IManagement/UpdateBranchResponse")]
        System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Branch> UpdateBranchAsync(string id, pl.lodz.p.ftims.edu.pai.central.dto.Branch project);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManagementChannel : pl.lodz.p.ftims.edu.pai.admin.AdminService.IManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagementClient : System.ServiceModel.ClientBase<pl.lodz.p.ftims.edu.pai.admin.AdminService.IManagement>, pl.lodz.p.ftims.edu.pai.admin.AdminService.IManagement {
        
        public ManagementClient() {
        }
        
        public ManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Project GetProject(string id) {
            return base.Channel.GetProject(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project> GetProjectAsync(string id) {
            return base.Channel.GetProjectAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Project[] GetProjects(int start, int limit) {
            return base.Channel.GetProjects(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project[]> GetProjectsAsync(int start, int limit) {
            return base.Channel.GetProjectsAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Project[] GetManagedProjects(string id, int start, int limit) {
            return base.Channel.GetManagedProjects(id, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project[]> GetManagedProjectsAsync(string id, int start, int limit) {
            return base.Channel.GetManagedProjectsAsync(id, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[] GetProjectTimesheetsForPeriod(string id, string start, string end) {
            return base.Channel.GetProjectTimesheetsForPeriod(id, start, end);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[]> GetProjectTimesheetsForPeriodAsync(string id, string start, string end) {
            return base.Channel.GetProjectTimesheetsForPeriodAsync(id, start, end);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Project[] QueryForProjects(string query, int start, int limit) {
            return base.Channel.QueryForProjects(query, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project[]> QueryForProjectsAsync(string query, int start, int limit) {
            return base.Channel.QueryForProjectsAsync(query, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Project CreateProject(pl.lodz.p.ftims.edu.pai.central.dto.CreateProject createProject1) {
            return base.Channel.CreateProject(createProject1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project> CreateProjectAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateProject createProject) {
            return base.Channel.CreateProjectAsync(createProject);
        }
        
        public void DeleteProject(string id) {
            base.Channel.DeleteProject(id);
        }
        
        public System.Threading.Tasks.Task DeleteProjectAsync(string id) {
            return base.Channel.DeleteProjectAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Project UpdateProject(string id, pl.lodz.p.ftims.edu.pai.central.dto.Project project) {
            return base.Channel.UpdateProject(id, project);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Project> UpdateProjectAsync(string id, pl.lodz.p.ftims.edu.pai.central.dto.Project project) {
            return base.Channel.UpdateProjectAsync(id, project);
        }
        
        public void SetProjectManager(string projectId, string employeeId) {
            base.Channel.SetProjectManager(projectId, employeeId);
        }
        
        public System.Threading.Tasks.Task SetProjectManagerAsync(string projectId, string employeeId) {
            return base.Channel.SetProjectManagerAsync(projectId, employeeId);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Employee GetProjectManager(string projectId) {
            return base.Channel.GetProjectManager(projectId);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> GetProjectManagerAsync(string projectId) {
            return base.Channel.GetProjectManagerAsync(projectId);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Task GetTask(string id) {
            return base.Channel.GetTask(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task> GetTaskAsync(string id) {
            return base.Channel.GetTaskAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Task[] GetTasks(int start, int limit) {
            return base.Channel.GetTasks(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task[]> GetTasksAsync(int start, int limit) {
            return base.Channel.GetTasksAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Task[] QueryForTaks(string query, int start, int limit) {
            return base.Channel.QueryForTaks(query, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task[]> QueryForTaksAsync(string query, int start, int limit) {
            return base.Channel.QueryForTaksAsync(query, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Task CreateTask(pl.lodz.p.ftims.edu.pai.central.dto.CreateTask createTask1) {
            return base.Channel.CreateTask(createTask1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task> CreateTaskAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateTask createTask) {
            return base.Channel.CreateTaskAsync(createTask);
        }
        
        public void DeleteTask(string id) {
            base.Channel.DeleteTask(id);
        }
        
        public System.Threading.Tasks.Task DeleteTaskAsync(string id) {
            return base.Channel.DeleteTaskAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Task UpdateTask(string id, pl.lodz.p.ftims.edu.pai.central.dto.Task project) {
            return base.Channel.UpdateTask(id, project);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Task> UpdateTaskAsync(string id, pl.lodz.p.ftims.edu.pai.central.dto.Task project) {
            return base.Channel.UpdateTaskAsync(id, project);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Employee GetEmployee(string id) {
            return base.Channel.GetEmployee(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> GetEmployeeAsync(string id) {
            return base.Channel.GetEmployeeAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Employee[] GetEmployees(int start, int limit) {
            return base.Channel.GetEmployees(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee[]> GetEmployeesAsync(int start, int limit) {
            return base.Channel.GetEmployeesAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Employee[] GetEmployeeSubordinates(string id, int start, int limit) {
            return base.Channel.GetEmployeeSubordinates(id, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee[]> GetEmployeeSubordinatesAsync(string id, int start, int limit) {
            return base.Channel.GetEmployeeSubordinatesAsync(id, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Employee GetEmployeeManager(string id) {
            return base.Channel.GetEmployeeManager(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> GetEmployeeManagerAsync(string id) {
            return base.Channel.GetEmployeeManagerAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[] GetEmployeeTimesheetsForPeriod(string id, string start, string end) {
            return base.Channel.GetEmployeeTimesheetsForPeriod(id, start, end);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[]> GetEmployeeTimesheetsForPeriodAsync(string id, string start, string end) {
            return base.Channel.GetEmployeeTimesheetsForPeriodAsync(id, start, end);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Employee CreateEmployee(pl.lodz.p.ftims.edu.pai.central.dto.CreateEmployee createEmployee1) {
            return base.Channel.CreateEmployee(createEmployee1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> CreateEmployeeAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateEmployee createEmployee) {
            return base.Channel.CreateEmployeeAsync(createEmployee);
        }
        
        public void DeleteEmployee(string id) {
            base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(string id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Employee UpdateEmployee(string id, pl.lodz.p.ftims.edu.pai.central.dto.Employee employee) {
            return base.Channel.UpdateEmployee(id, employee);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee> UpdateEmployeeAsync(string id, pl.lodz.p.ftims.edu.pai.central.dto.Employee employee) {
            return base.Channel.UpdateEmployeeAsync(id, employee);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Employee[] AddSubordinate(string employeeId, string subordinateId) {
            return base.Channel.AddSubordinate(employeeId, subordinateId);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee[]> AddSubordinateAsync(string employeeId, string subordinateId) {
            return base.Channel.AddSubordinateAsync(employeeId, subordinateId);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Employee[] DeleteSubordinate(string employeeId, string subordinateId) {
            return base.Channel.DeleteSubordinate(employeeId, subordinateId);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Employee[]> DeleteSubordinateAsync(string employeeId, string subordinateId) {
            return base.Channel.DeleteSubordinateAsync(employeeId, subordinateId);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Timesheet GetTimesheet(string id) {
            return base.Channel.GetTimesheet(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet> GetTimesheetAsync(string id) {
            return base.Channel.GetTimesheetAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[] GetTimesheets(int start, int limit) {
            return base.Channel.GetTimesheets(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[]> GetTimesheetsAsync(int start, int limit) {
            return base.Channel.GetTimesheetsAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[] GetTimesheetsNeedAction(string id, int start, int limit) {
            return base.Channel.GetTimesheetsNeedAction(id, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet[]> GetTimesheetsNeedActionAsync(string id, int start, int limit) {
            return base.Channel.GetTimesheetsNeedActionAsync(id, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Audit[] GetTimesheetHistory(string id, int start, int limit) {
            return base.Channel.GetTimesheetHistory(id, start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Audit[]> GetTimesheetHistoryAsync(string id, int start, int limit) {
            return base.Channel.GetTimesheetHistoryAsync(id, start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Timesheet CreateTimesheet(pl.lodz.p.ftims.edu.pai.central.dto.CreateTimesheet createTimesheet1) {
            return base.Channel.CreateTimesheet(createTimesheet1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet> CreateTimesheetAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateTimesheet createTimesheet) {
            return base.Channel.CreateTimesheetAsync(createTimesheet);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Timesheet AcceptTimesheet(string id, string employeeId) {
            return base.Channel.AcceptTimesheet(id, employeeId);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet> AcceptTimesheetAsync(string id, string employeeId) {
            return base.Channel.AcceptTimesheetAsync(id, employeeId);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Timesheet RejectTimesheet(string id, string employeeId) {
            return base.Channel.RejectTimesheet(id, employeeId);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Timesheet> RejectTimesheetAsync(string id, string employeeId) {
            return base.Channel.RejectTimesheetAsync(id, employeeId);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Branch GetBranch(string id) {
            return base.Channel.GetBranch(id);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Branch> GetBranchAsync(string id) {
            return base.Channel.GetBranchAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Branch[] GetBranchess(int start, int limit) {
            return base.Channel.GetBranchess(start, limit);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Branch[]> GetBranchessAsync(int start, int limit) {
            return base.Channel.GetBranchessAsync(start, limit);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Branch CreateBranch(pl.lodz.p.ftims.edu.pai.central.dto.CreateBranch createBranch1) {
            return base.Channel.CreateBranch(createBranch1);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Branch> CreateBranchAsync(pl.lodz.p.ftims.edu.pai.central.dto.CreateBranch createBranch) {
            return base.Channel.CreateBranchAsync(createBranch);
        }
        
        public void DeleteBranch(string id) {
            base.Channel.DeleteBranch(id);
        }
        
        public System.Threading.Tasks.Task DeleteBranchAsync(string id) {
            return base.Channel.DeleteBranchAsync(id);
        }
        
        public pl.lodz.p.ftims.edu.pai.central.dto.Branch UpdateBranch(string id, pl.lodz.p.ftims.edu.pai.central.dto.Branch project) {
            return base.Channel.UpdateBranch(id, project);
        }
        
        public System.Threading.Tasks.Task<pl.lodz.p.ftims.edu.pai.central.dto.Branch> UpdateBranchAsync(string id, pl.lodz.p.ftims.edu.pai.central.dto.Branch project) {
            return base.Channel.UpdateBranchAsync(id, project);
        }
    }
}
